### ISSUE TITLE
Failed to resolve: com.github.thunderrise:android-animations:-SNAPSHOT

### ISSUE THREAD

**Issue by lvprasad-ns** [thunderrise/android-TNRAnimationHelper#1]
![11](https://cloud.githubusercontent.com/assets/16414746/19923930/b36464e0-a10f-11e6-807f-08d45b55d75b.PNG)

**Comment by chowaikong** [comment]
Same here.

**Comment by nisd93** [comment]
@lvprasad-ns @chowaikong  Other workaround if you fail to run app ,
 Add  **compile project(':animations')**

**Comment by itretyak** [comment]
@lvprasad-ns @chowaikong we made some changes. Try again with
 `compile 'com.github.thunderrise:android-TNRAnimationHelper:-SNAPSHOT'`

**Comment by nisd93** [comment]
@itretyak Its working now, Thanks!

**Comment by alikamts** [comment]
same here :-(

**Comment by alikamts** [comment]
same 💯
